apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.104
    helm:
      values: |
        controller:
          image:
            registry: docker.io
            repository: jenkins/jenkins
            tag: "2.516.1-lts-jdk17"
          serviceType: NodePort
          servicePort: 8080
          nodePort: 32000
          agentListenerPort: 50000
          
          # [핵심] 의존성 자동 해결
          installLatestPlugins: true
          installLatestSpecifiedPlugins: true
          installPlugins:
            - configuration-as-code
            - job-dsl
            - kubernetes
            - workflow-aggregator
            - docker-workflow
            - gitlab-plugin
            - blueocean
            - credentials-binding
            - credentials
            - plain-credentials
            - json-path-api
            - aws-credentials

          # 관리자 계정 연동 (아래에 생성할 시크릿과 연결)
          admin:
            existingSecret: "jenkins-admin-secret"
            userKey: "jenkins-admin-user"
            passwordKey: "jenkins-admin-password"

          JCasC:
            defaultConfig: true
            configScripts:
              all-jenkins-config: |
                jenkins:
                  systemMessage: "Jenkins configured automatically by ArgoCD"
                  clouds:
                    - kubernetes:
                        name: "kubernetes"
                        serverUrl: "https://kubernetes.default.svc"
                        namespace: "jenkins"
                        jenkinsUrl: "http://jenkins-stack:8080"
                        jenkinsTunnel: "jenkins-stack-agent:50000"
                        templates:
                          - name: "jenkins-agent"
                            label: "jenkins-agent"
                            containers:
                              - name: "jnlp"
                                image: "jenkins/inbound-agent:3206.vb_15dcf73f6a_9-1"
                                args: "^${computer.jnlpmac} ^${computer.name}"
                unclassified:
                  gitLabConnectionConfig:
                    connections:
                      - name: "my-gitlab"
                        url: "http://192.168.72.131"
                        apiTokenId: "gitlab-token-id"
                        clientBuilderId: "autodetect"
                        ignoreCertificateErrors: true
        
        agent:
          enabled: true
          serviceType: ClusterIP
          port: 50000

        persistence:
          enabled: true
          existingClaim: jenkins-pvc
          storageClass: "local-path"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
