apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.104
    helm:
      values: |
        controller:
          image:
            registry: docker.io
            repository: jenkins/jenkins
            tag: "2.516.1-lts-jdk17"
          serviceType: NodePort
          servicePort: 8080
          nodePort: 32000
          agentListenerPort: 50000

          admin:
            existingSecret: "jenkins-stack"
            userKey: "jenkins-admin-user"
            passwordKey: "jenkins-admin-password"

          installPlugins:
            - configuration-as-code
            - job-dsl
            - kubernetes
            - workflow-aggregator
            - gitlab-plugin
            - credentials-binding
            - credentials
            - plain-credentials
            - aws-credentials

          # 젠킨스 시스템 환경변수로 토큰 주입 (가장 확실한 전달 방식)
          containerEnv:
            - name: GITLAB_TOKEN_ENV
              valueFrom:
                secretKeyRef:
                  name: gitlab-api-secret
                  key: api-token

          JCasC:
            defaultConfig: true
            configScripts:
              all-config: |
                jenkins:
                  systemMessage: "Jenkins configured automatically by ArgoCD"
                  clouds:
                    - kubernetes:
                        name: "kubernetes"
                        serverUrl: "https://kubernetes.default.svc"
                        namespace: "jenkins"
                        jenkinsUrl: "http://jenkins-stack:8080"
                        jenkinsTunnel: "jenkins-stack-agent:50000"
                        templates:
                          - name: "jenkins-agent"
                            label: "jenkins-agent"
                            containers:
                              - name: "jnlp"
                                image: "jenkins/inbound-agent:3206.vb_15dcf73f6a_9-1"
                                args: "^${computer.jnlpmac} ^${computer.name}"
                
                # Global 크리덴셜 명시적 등록
                credentials:
                  system:
                    domainCredentials:
                      - credentials:
                          - usernamePassword:
                              scope: GLOBAL
                              id: "gitlab-checkout-cred"
                              username: "root"
                              password: "${GITLAB_TOKEN_ENV}" # 위에서 주입한 환경변수 참조
                
                jobs:
                  - script: >
                      pipelineJob('jenkins-test-pipeline') {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("http://192.168.72.131/root/app-repo.git")
                                  credentials('gitlab-checkout-cred')
                                }
                                branches('*/main')
                              }
                            }
                            scriptPath('Jenkinsfile')
                          }
                        }
                      }
                
                unclassified:
                  gitLabConnectionConfig:
                    connections:
                      - name: "my-gitlab"
                        url: "http://192.168.72.131"
                        apiTokenId: "gitlab-checkout-cred" # 파이프라인과 ID 동일하게 일치시킴
                        clientBuilderId: "autodetect"
                        ignoreCertificateErrors: true

        agent:
          enabled: true
          serviceType: ClusterIP
          port: 50000

        persistence:
          enabled: true
          existingClaim: jenkins-pvc
          storageClass: "local-path"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
