apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    # 프로메테우스 커뮤니티 공식 헬름 레포지토리 주소
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 56.6.2  # 최신 안정화 버전 계열
    helm:
      # 필요한 컴포넌트들을 true로 켜서 헬름이 한방에 빌드하게 만듬
      values: |
        prometheus:
          enabled: true
        grafana:
          enabled: true
        alertmanager:
          enabled: true
        kube-state-metrics:
          enabled: true
        prometheus-node-exporter:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # 🌟 추가된 부분: CRD 용량 초과 에러 방지를 위한 서버 사이드 어플라이
    syncOptions:
    - ServerSideApply=true
