apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
  namespace: jenkins
type: Opaque
stringData:
  access-key: "AKIAV5QZ3ZUYN5HIFSNI"          #junsu access key
  secret-key: "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"   # junsu secret-key
