apiVersion: v1
kind: Secret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
type: Opaque
data:
  jenkins-admin-user: YWRtaW4=    
  jenkins-admin-password: YXJteTY= 
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-stack
  namespace: jenkins
type: Opaque
data:
  jenkins-admin-user: YWRtaW4=    
  jenkins-admin-password: YXJteTY= 
